sudo: required
# dist: trusty - not active so far
language: bash

env:
  global:
    - OCTOKIT_API_ENDPOINT="https://github.wdf.sap.corp/api/v3"
    - SHUNIT_COLOR='always'
    - COMMIT=${TRAVIS_COMMIT::8}
    - BUILD_COMMIT=b${TRAVIS_BUILD_NUMBER}-g${COMMIT}

os:
  - linux
#  - osx

# addons: - section is not valid
#    apt:
#     sources:
#     - debian-sid    # Grab shellcheck from the Debian repo (o_O)
#      packages:
#      - shellcheck

before_install:
    #MY_RELEASE is not availalbe within env:global
    - if [[ ${MY_RELEASE} -eq 1 ]]; then
        VERSION_BUILD_COMMIT=v${_VERSION}-${BUILD_COMMIT};
      else
        VERSION_BUILD_COMMIT=v${_VERSION}-dev-${BUILD_COMMIT};
      fi
    - sudo apt-add-repository "deb http://archive.ubuntu.com/ubuntu trusty-backports main restricted universe multiverse"
    - sudo apt-get -qq update
    - sudo apt-get -t trusty-backports install shellcheck
    - sudo pip install bashate

script:
  # Run unit tests - runs all the unit tests that can be found, and generates a nice report of the tests
  - bash -c 'cd ./scripts/tests/; ./test_runner'
  # - bash -c 'shopt -s globstar; bashate scripts/**/*.{sh,check}'
  - bash -c 'shopt -s globstar; bashate -i E006 scripts/bin/saphana* scripts/bin/lib*'
  - bash -c 'shopt -s globstar; bashate -i E006 scripts/**/*.check'
  

after_success:
    - mkdir -p build/saphana-checks
    - cp -rp ./scripts/bin build/saphana-checks
    - cp -rp ./scripts/lib build/saphana-checks

    # modifiy VERSION & DATE 
    - perl ./helperscripts/replace-version.pl build/saphana-checks/bin/saphana-check.sh ${VERSION_BUILD_COMMIT}
    - diff build/saphana-checks/bin/saphana-check.sh scripts/bin/saphana-check.sh

    - perl ./helperscripts/replace-version.pl build/saphana-checks/bin/saphana-helper-funcs ${VERSION_BUILD_COMMIT}
    - diff build/saphana-checks/bin/saphana-helper-funcs scripts/bin/saphana-helper-funcs

    - perl ./helperscripts/replace-version.pl build/saphana-checks/bin/saphana-logger ${VERSION_BUILD_COMMIT}
    - diff build/saphana-checks/bin/saphana-logger scripts/bin/saphana-logger

    - ls -R build/

# matrix:
#   fast_finish: true

before_deploy:
    - if [[ ${MY_RELEASE} -eq 1 ]]; then
        TAR_VERSION=v${_VERSION};
      else
        TAR_VERSION=v${_VERSION}-dev-${BUILD_COMMIT};
      fi
   # Set up git user name and tag this commit
   # - git config --local user.name "d027354"
   # - git config --local user.email "peter.pitterling@sap.com"
   # - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
   # - git tag "v$_VERSION-b$TRAVIS_BUILD_NUMBER-g$COMMIT"

    - curl -k https://github.wdf.sap.corp/raw/GitHub/Install-Root-Certificates/master/install-certs-ubuntu-12.04.sh | sudo -E sh

    # create zipped tarball
    - sudo chmod -R 444 build/saphana-checks
    - sudo chmod 744 build/saphana-checks/bin/saphana-check.sh
    - sudo chown -R root:root build/saphana-checks
    - sudo tar -czf build/saphana-checks-${TAR_VERSION}.tgz --directory=./build saphana-checks
    - sha256sum build/saphana-checks-${TAR_VERSION}.tgz > build/saphana-checks-${TAR_VERSION}.tgz.sha256
    - ls -l build/
    - tar -tvf build/saphana*.tgz

deploy:
  provider: releases
  prerelease: true
  body: Travis build on [${TRAVIS_BRANCH}](https://travis-ci.mo.sap.corp/SAP-COE-HPTI/saphana-checks/builds/${TRAVIS_BUILD_ID})
  api_key:
    secure: aQnueMZKDNLrM8J9oLlPItJ+qUMqj1Dm9demLPGwPD0j66jtSUFIV7ioR84FILLqklY0mPDCrfjCN2klYp6NJDGRQuKIQZaNdHQTY1rKUJQyS23MQ03ASf2F0PE3vk4t3fm1XBD2IKjP/4m8BBfx/LV41AXv35CG217I0ryrtluPkU8Mjx8j/bNZZLA9/NeapNcjdMxeV6uTWrmcOYY7dYEuUAXws7UWU4+qY7PzGQQemPJmXpNS8jtlMS0aUVETI/L+Irs8NouoeoMrsfzs876jpc0AH3tG+2q6Foc8EB/ivGC1Amq3pia1asoKQ0CtUOfiDRuPcOAVjnn0+/eAJueOgd3gf6JuG8SWO6HUrpF6eRNE1gk9HP/kKj5CxfR1PqUw08UDok2VMYCS2prFPljaihZ5jCcCzYJN1iDS2ejmI+xf4xFT2opGaH21zEzJlimv8vAlmm0gc3mce3tXawD31cpWariMt5fQdLbM1RnkcJ5OM0am3lyqEUqVmB/rmUwwAXUgFjm6Ng7vnkCW3bPvLptEJ5PUGmbAyl4oAbSUEF0G0JeSrk0VKXIftMmm5TzrRR/8xKLq1jOL00fsFeQIiz6A5sPz2Fs1Wlbb/hBr32HlzZxa83sTWIA/aNfWz0W6B8BlzqC1Fkyp4IGHeM6vVMjXD11vbKb9URG761E=
  file_glob: true
  file: "build/saphana-checks-*.tgz*"
  skip_cleanup: true
  on:
    repo: SAP-COE-HPTI/saphana-checks
    all_branches: true
    tags: true

  # provider: releases
  # prerelease: false
  # draft: true
  # body: Travis build on [RELEASE] - https://travis-ci.mo.sap.corp/SAP-COE-HPTI/saphana-checks/builds/${TRAVIS_BUILD_ID}
  # api_key:
  #   secure: aQnueMZKDNLrM8J9oLlPItJ+qUMqj1Dm9demLPGwPD0j66jtSUFIV7ioR84FILLqklY0mPDCrfjCN2klYp6NJDGRQuKIQZaNdHQTY1rKUJQyS23MQ03ASf2F0PE3vk4t3fm1XBD2IKjP/4m8BBfx/LV41AXv35CG217I0ryrtluPkU8Mjx8j/bNZZLA9/NeapNcjdMxeV6uTWrmcOYY7dYEuUAXws7UWU4+qY7PzGQQemPJmXpNS8jtlMS0aUVETI/L+Irs8NouoeoMrsfzs876jpc0AH3tG+2q6Foc8EB/ivGC1Amq3pia1asoKQ0CtUOfiDRuPcOAVjnn0+/eAJueOgd3gf6JuG8SWO6HUrpF6eRNE1gk9HP/kKj5CxfR1PqUw08UDok2VMYCS2prFPljaihZ5jCcCzYJN1iDS2ejmI+xf4xFT2opGaH21zEzJlimv8vAlmm0gc3mce3tXawD31cpWariMt5fQdLbM1RnkcJ5OM0am3lyqEUqVmB/rmUwwAXUgFjm6Ng7vnkCW3bPvLptEJ5PUGmbAyl4oAbSUEF0G0JeSrk0VKXIftMmm5TzrRR/8xKLq1jOL00fsFeQIiz6A5sPz2Fs1Wlbb/hBr32HlzZxa83sTWIA/aNfWz0W6B8BlzqC1Fkyp4IGHeM6vVMjXD11vbKb9URG761E=
  # file_glob: true
  # file: "build/saphana-checks-*.tgz*"
  # skip_cleanup: true
  # on:
  #   repo: SAP-COE-HPTI/saphana-checks
  #   all_branches: true
  #   tags: true
  #   condition: $MY_RELEASE = true
