dist: xenial
language: bash
cache: pip

env:
  global:
    - OCTOKIT_API_ENDPOINT="https://github.wdf.sap.corp/api/v3"
    - SHUNIT_COLOR='always'
    - COMMIT=${TRAVIS_COMMIT::8}

os:
  - linux
#  - osx

before_install:
    #TRAVIS_BRANCH=TRAVIS_TAG if tagged
    - |
      if [[ $TRAVIS_BRANCH =~ ^v([0-9]+)\-(.*)$ ]]; then
        _VERSION=${BASH_REMATCH[1]}
        _RELEASE=${BASH_REMATCH[2]}
      else
        _VERSION='9999'
        _RELEASE='0.1.beta0'
      fi
    - RELEASE_COMMIT=${_RELEASE}.g${COMMIT}
    - VERSION_BUILD_COMMIT=${_VERSION}-${RELEASE_COMMIT}

    - echo "[INFO] _BRANCH > $TRAVIS_BRANCH ; _VERSION> $_VERSION ; VERSION_BUILD_COMMIT> $VERSION_BUILD_COMMIT"

    # - sudo -H pip install --upgrade pip

install:
    - sudo -H pip install bashate

script:
  # Run unit tests - runs all the unit tests that can be found
  - bash -c 'cd ./scripts/tests/; ./test_runner'
  - bash -c 'cd ./scripts/tests/; ./test_runner -t "$(echo ./check/*_test.sh)"'

  # remove check_staging_area
  - rm -rf ./scripts/lib/check_staging_area

  # Syntax checking
  - bash -c 'shellcheck --version'
  - bash -c 'cd scripts/bin; shellcheck --external-sources ./saphana-* ./lib*'
  - bash -c 'shopt -s globstar; shellcheck --exclude=SC2154 scripts/**/*.check'

  # Code format checking
  # - bash -c 'shopt -s globstar; bashate scripts/**/*.{sh,check}'
  - bash -c 'bashate -i E006,E043 scripts/bin/saphana*'
  - bash -c 'bashate -i E006 scripts/bin/lib*'
  - bash -c 'shopt -s globstar; bashate -i E006,E010 scripts/**/*.check'


after_success:
    - mkdir -p build/opt/sap/saphana-checks
    - cp -rp ./scripts/{bin,lib} build/opt/sap/saphana-checks

    # modifiy VERSION & DATE
    - perl ./buildscripts/replace-version.pl build/opt/sap/saphana-checks/bin/saphana-check.sh ${VERSION_BUILD_COMMIT}
    - diff build/opt/sap/saphana-checks/bin/saphana-check.sh scripts/bin/saphana-check.sh

    - perl ./buildscripts/replace-version.pl build/opt/sap/saphana-checks/bin/saphana-helper-funcs ${VERSION_BUILD_COMMIT}
    - diff build/opt/sap/saphana-checks/bin/saphana-helper-funcs scripts/bin/saphana-helper-funcs

    - perl ./buildscripts/replace-version.pl build/opt/sap/saphana-checks/bin/saphana-logger ${VERSION_BUILD_COMMIT}
    - diff build/opt/sap/saphana-checks/bin/saphana-logger scripts/bin/saphana-logger

    - ls -R build/


before_deploy:
    # Prepare Ownership and Permissions
    - sudo chmod -R 444 build/opt/sap/saphana-checks
    - sudo chmod 755 build/opt/sap/saphana-checks/bin/saphana-check.sh
    - sudo chown -R root:root build/opt/sap/saphana-checks

    # create rpm
    - sudo apt-get install --no-install-recommends -y rpm
    - echo "[INFO] PWD> $PWD"
    - echo "[INFO] _VERSION> $_VERSION"
    - echo "[INFO] RELEASE_COMMIT> $RELEASE_COMMIT"
    - sudo rpmbuild -v -bb --buildroot='/home/travis/build/SAP-COE-HPTI/saphana-checks/build' --define "_version ${_VERSION}" --define "_release ${RELEASE_COMMIT}" ./buildscripts/saphana-checks-rpm.spec
    - bash -c "cd /home/travis/rpmbuild/RPMS/noarch; rpm -Kv saphana-checks-${VERSION_BUILD_COMMIT}.noarch.rpm > /home/travis/build/SAP-COE-HPTI/saphana-checks/build/saphana-checks-${VERSION_BUILD_COMMIT}.noarch.rpm.digest"

    # create zipped tarball
    - sudo tar -czf build/saphana-checks-${VERSION_BUILD_COMMIT}.tgz --directory=./build/opt/sap saphana-checks
    - sha256sum build/saphana-checks-${VERSION_BUILD_COMMIT}.tgz > build/saphana-checks-${VERSION_BUILD_COMMIT}.tgz.sha256
    - ls -l build/
    - tar -tvf build/saphana-checks-*.tgz


deploy:
  provider: releases
  prerelease: true
  draft: true
  body: Travis build on [${TRAVIS_BRANCH}](${TRAVIS_BUILD_WEB_URL})
  api_key:
    secure: ReXcT4pYLK+ynD6udR8bU/gUK9sJuLt9IlYM3DmsoA7lQrqqqjQ45xyFYGi8YvlVpkyTjPkjQ0lb9iBxj6mTjaA8Ct3GD9y8eKs34eJIX6TXDxoSmpqIQ0seDzy6HhUBl6krNpivHmrOLhtdFUvU90whON9lex/9lGnGjIKNuEsLy1OZk05g50Yb+uW2qQzDrHPJLo5R5ShDu4kypm+M6K/Mw5nZE3PhPhn4UCv30I7K6aqTsVuo7KNCOh5ZfFulhzz58NmF6843WFAihHcspefuNMPokRZkNjPWh5Q5tZ+B51/xSCAFWGhYy7pVuzLfNzi8TQ5WLWuIuEarhNP1+EqwBs2G3Lng4NJr5wlaMcQHCKa+JFseuB7Ay3TNjSLJx+M7Rf9bauhW9nTp4JALZbPK1RbTM3otnfSfssEuLCYZFvIV/SBJydFJHowV9K8QNT2MLrY2PtSOIg+tBLvgSxx8IU4Y7sfYT96tcaDSeUgfqrYW6jf+jHGyHNe9HQzylJPKRvqQZ2xZfRxCtnPCyYqmdErYYcChjFfHNnsOmn5n/PKFLU68zaDQPjMzjka4Bi+c8H9wJywJFbdVaR9u2BM9AZkaGEjzwxIgnca7jAobb4GxLe/F5EpCf3pN1AEgAGgOWEvv3UmITScHCMf0TUxDUh4HUbLongiNHx+xUUc=
  file_glob: true
  file:
    - "build/saphana-checks-*.tgz*"
    - "/home/travis/rpmbuild/RPMS/noarch/saphana-checks-*.noarch.rpm*"
    - "build/saphana-checks-*.noarch.rpm.digest"
  skip_cleanup: true
  on:
    repo: SAP-COE-HPTI/saphana-checks
    all_branches: true
    tags: true