#!/bin/bash
umask 0027

#------------------------------------------------------------------
# SAP HANA OS checks
#------------------------------------------------------------------
# (C) Copyright SAP 2017-2019
# Author: DBS - CoE EMEA HANA Platform & Technical Infrastructure
#
# Script name: "saphana-logger-stubs"
#
# Logging Functions - Stubs for Testing
#------------------------------------------------------------------

# return if saphana-logger-stubs already loaded
[[ -n "${HANA_LOGGER_STUBS:-}" ]] && return 0
HANA_LOGGER_STUBS='stubs'

logNotify()  { : ; }
logError()  { : ; }
logWarn()  { : ; }
logInfo()  { : ; }
logDebug()  { : ; }
logTrace()  { : ; }

logCheckSkipped()  { : ; }
logCheckInfo()  { : ; }
logCheckOk()  { : ; }
logCheckError()  { : ; }
logCheckWarning()  { : ; }

