name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    # branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: [HPTI]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Show environment
        run: |
          pwd
          env

      # Runs a set of commands using the runners shell
      - name: Syntax checking BIN
        run: |
          shellcheck --external-sources ./saphana-* ./lib*
        working-directory: ./scripts/bin

      # Runs a set of commands using the runners shell
      - name: Syntax checking CHECKS
        run: |
          shopt -s globstar; shellcheck scripts/**/*.check

      # Runs a set of commands using the runners shell
      - name: Run unit tests
        run: |
          ./test_runner
          ./test_runner -t "$(echo ./check/*_test.sh)"
        working-directory: ./scripts/tests
        env:
          SHUNIT_COLOR: always

      # Runs a set of commands using the runners shell - requires pip install bashate - install @ self-hosted
      - name: Code format checking - bashate
        run: |
          bashate -i E006,E043 scripts/bin/saphana*
          bashate -i E006 scripts/bin/lib*
          shopt -s globstar; bashate -i E006,E010 scripts/**/*.check

      # Runs a set of commands using the runners shell - requires shfmt - install @ self-hosted
      - name: Code format checking - shfmt
        run: |
          shfmt --indent 4 -ci -sr -kp --diff scripts/bin || true
          shopt -s globstar; shfmt --indent 4 -ci -sr -kp --diff scripts/**/*.check || true
          shopt -s globstar; shfmt --indent 4 -ci -sr -kp --diff scripts/tests/**/*_test.sh || true

